SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT ID, i.FISH_TYPE, i.LENGTH
    FROM FISH_INFO i
    INNER JOIN (
        SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE) AS st
    ON st.LENGTH = i.LENGTH AND st.FISH_TYPE = i.FISH_TYPE
) AS st2
LEFT JOIN FISH_NAME_INFO AS n
ON n.FISH_TYPE = st2.FISH_TYPE
